name: hummingbot-helper
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pydantic
  - langchain
  - openai
  - jupyter
  - pip
  - pip:
    - tiktoken
    - python-dotenv
    - chromadb
    - lark
    - streamlit
    - watchdog
    - httpx
    - bs4
    - markdownify